/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email and password, receiving a session cookie */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and immediately log in, receiving a session cookie */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The currently authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search categories for the widget-form combobox */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/widgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List widgets — server-side pagination, sorting, filtering */
        get: operations["listWidgets"];
        put?: never;
        /** Create a widget */
        post: operations["createWidget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/widgets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** Get a single widget */
        get: operations["getWidget"];
        put?: never;
        post?: never;
        /** Delete a widget */
        delete: operations["deleteWidget"];
        options?: never;
        head?: never;
        /** Partially update a widget */
        patch: operations["updateWidget"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            readonly id: number;
            /** Format: email */
            email: string;
            name: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RegisterRequest: {
            email: components["schemas"]["User"]["email"];
            name: components["schemas"]["User"]["name"];
            password: components["schemas"]["LoginRequest"]["password"];
        };
        Category: {
            readonly id: number;
            name: string;
        };
        /**
         * @description Enum field — forces Select input + badge rendering (Phase 4).
         * @enum {string}
         */
        WidgetStatus: "draft" | "active" | "archived";
        /** @description The six properties below are the Phase 4 field-type requirements — one field per force, so each maps unambiguously to the UI pattern it exercises. Do not add a seventh; see docs/BUILD-PLAN.md Scope Ceiling. */
        Widget: {
            readonly id: number;
            /** @description Display label. Not one of the six forcing field types. */
            name: string;
            /** @description Foreign key to Category.id — forces a combobox with async search (Phase 4). Required: every widget belongs to a category. */
            categoryId: number;
            /** @default draft */
            status: components["schemas"]["WidgetStatus"];
            /**
             * Format: date-time
             * @description Datetime field — forces a date picker plus timezone handling (Phase 4). ISO 8601 with offset, e.g. "2026-09-15T00:00:00Z".
             */
            availableFrom: string;
            /**
             * Format: email
             * @description Nullable field — forces empty-state display when null and optional (not required-when-present) validation (Phase 4).
             */
            assigneeEmail?: string | null;
            /** @description Decimal field, represented as a fixed-2-decimal-place string (never a float) to avoid binary rounding on money — forces locale-aware formatting on display and parsing on input (Phase 4). Example: "19.99". */
            price: string;
            /** @description Long-text field — forces a textarea on the form and truncation in the table (Phase 4). */
            description: string;
        };
        /** @description Widget without a server-assigned id. */
        WidgetCreate: {
            name: components["schemas"]["Widget"]["name"];
            categoryId: components["schemas"]["Widget"]["categoryId"];
            status: components["schemas"]["WidgetStatus"];
            availableFrom: components["schemas"]["Widget"]["availableFrom"];
            assigneeEmail?: components["schemas"]["Widget"]["assigneeEmail"];
            price: components["schemas"]["Widget"]["price"];
            description: components["schemas"]["Widget"]["description"];
        };
        /** @description All fields optional — PATCH semantics. */
        WidgetUpdate: {
            name?: components["schemas"]["Widget"]["name"];
            categoryId?: components["schemas"]["Widget"]["categoryId"];
            status?: components["schemas"]["WidgetStatus"];
            availableFrom?: components["schemas"]["Widget"]["availableFrom"];
            assigneeEmail?: components["schemas"]["Widget"]["assigneeEmail"];
            price?: components["schemas"]["Widget"]["price"];
            description?: components["schemas"]["Widget"]["description"];
        };
        /** @description Wire pagination shape — deliberately not Page<T>. The gateway computes page/pageSize from offset/limit; see src/api/gateway/. */
        WidgetListResponse: {
            items: components["schemas"]["Widget"][];
            total: number;
        };
        /** @description FastAPI's default 422 shape (RequestValidationError). */
        ValidationErrorBody: {
            detail: {
                loc: (string | number)[];
                msg: string;
                type: string;
            }[];
        };
        /** @description FastAPI's default HTTPException shape. */
        HTTPErrorBody: {
            detail: string;
        };
    };
    responses: {
        /** @description Validation failed on one or more fields. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorBody"];
            };
        };
        /** @description Resource not found. */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["HTTPErrorBody"];
            };
        };
        /** @description Missing or invalid credentials. */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["HTTPErrorBody"];
            };
        };
        /** @description Unhandled server error. */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["HTTPErrorBody"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated. Sets the session_id cookie. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["ServerError"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registered and authenticated. Sets the session_id cookie. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            422: components["responses"]["ValidationError"];
            500: components["responses"]["ServerError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out (always, whether or not a session existed). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["ServerError"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["ServerError"];
        };
    };
    listCategories: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring match on name. */
                search?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching categories, unpaginated (typeahead result set, not a table). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["ServerError"];
        };
    };
    listWidgets: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                /** @description Single sort field and direction, e.g. "name:asc". */
                sort?: string;
                status?: components["schemas"]["WidgetStatus"];
                categoryId?: number;
                /** @description Case-insensitive substring match on name. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of widgets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WidgetListResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["ServerError"];
        };
    };
    createWidget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WidgetCreate"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Widget"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["ServerError"];
        };
    };
    getWidget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Widget"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["ServerError"];
        };
    };
    deleteWidget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["ServerError"];
        };
    };
    updateWidget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WidgetUpdate"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Widget"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["ServerError"];
        };
    };
}
