/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email and password, receiving a session cookie */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and immediately log in, receiving a session cookie */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The currently authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/environment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Which data the backend is serving, for DataEnvironmentBanner
         * @description Needs no session: the banner shows on /login too. A null dataLabel means production data, and no banner. The backend's DATA_LABEL.
         */
        get: operations["getDataEnvironment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/widget-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search widget categories for the widget-form combobox */
        get: operations["listWidgetCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/widgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List widgets — server-side pagination, sorting, filtering */
        get: operations["listWidgets"];
        put?: never;
        /** Create a widget */
        post: operations["createWidget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/widgets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** Get a single widget */
        get: operations["getWidget"];
        put?: never;
        post?: never;
        /** Delete a widget */
        delete: operations["deleteWidget"];
        options?: never;
        head?: never;
        /** Partially update a widget */
        patch: operations["updateWidget"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DataEnvironment: {
            /** @description What the data is, as the banner names it ("dev" shows "Dev data"). null when the backend serves production data. */
            dataLabel: string | null;
        };
        User: {
            readonly id: number;
            /** Format: email */
            email: string;
            name: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RegisterRequest: {
            email: components["schemas"]["User"]["email"];
            name: components["schemas"]["User"]["name"];
            password: components["schemas"]["LoginRequest"]["password"];
        };
        /** @description The widget's reference entity: what categoryId and extraCategoryIds point at. Named for the widget, so an app's own Category entity never collides with the demo's. */
        WidgetCategory: {
            readonly id: number;
            name: string;
        };
        /**
         * @description Enum field — forces Select input + badge rendering (Phase 4).
         * @enum {string}
         */
        WidgetStatus: "draft" | "active" | "archived";
        /**
         * @description One option of the multi-choice tags field.
         * @enum {string}
         */
        WidgetTag: "fragile" | "bulky" | "seasonal" | "featured";
        /** @description One property per field type the foundation supports, so each maps unambiguously to the UI pattern it exercises and /new-entity has a reference to copy (docs/entities/widget.md). Six came from Phase 4; tags (multi choice) was added in Phase G because a real project needed it; inStock (yes/no) in 3.4.0, extraCategoryIds (multi reference) in 3.5.0, checklist (sub-records) in 3.6.0 and checklistState (computed) in 3.7.0 for the Task Dashboard app. Add a type only when a real app needs one. */
        Widget: {
            readonly id: number;
            /** @description Display label. Not one of the six forcing field types. */
            name: string;
            /** @description Foreign key to WidgetCategory.id — forces a combobox with async search (Phase 4). Required: every widget belongs to a category. */
            categoryId: number;
            /** @default draft */
            status: components["schemas"]["WidgetStatus"];
            /**
             * Format: date-time
             * @description Datetime field — forces a date picker plus timezone handling (Phase 4). ISO 8601 with offset, e.g. "2026-09-15T00:00:00Z".
             */
            availableFrom: string;
            /**
             * Format: email
             * @description Nullable field — forces empty-state display when null and optional (not required-when-present) validation (Phase 4).
             */
            assigneeEmail?: string | null;
            /** @description Decimal field, represented as a fixed-2-decimal-place string (never a float) to avoid binary rounding on money — forces locale-aware formatting on display and parsing on input (Phase 4). Example: "19.99". */
            price: string;
            /** @description Long-text field — forces a textarea on the form and truncation in the table (Phase 4). */
            description: string;
            /** @description Multi-choice field — forces a multi-select combobox with chips on the form, badges in the table, and an any-of list filter (Phase G). Always present on read; empty when none are chosen. */
            tags: components["schemas"]["WidgetTag"][];
            /**
             * @description Yes/no field — forces a switch on the form, a Yes/No cell in the table and an either/yes/no list filter. Never null: always present on read, true when a create leaves it out.
             * @default true
             */
            inStock: boolean;
            /** @description Multi-reference field — links to any number of WidgetCategory records by id. Forces a multi-select combobox with async search and chips on the form (names fetched with GET /widget-categories?ids=...), names as badges in the table, and an any-of list filter. Always present on read, in ascending id order; empty when none. An id that isn't a category is a 422 field error. */
            extraCategoryIds: number[];
            /** @description Sub-records — an ordered list of items that belong to this widget alone, edited on its form and saved with it. Forces a list editor (add, remove, move up/down) on the form and a done-count in the table. Always present on read, in the order saved; empty when none. A field error inside an item is keyed by its path, e.g. loc ["body", "checklist", 2, "text"]. */
            checklist: components["schemas"]["ChecklistItem"][];
            /** @description Computed, read-only field — worked out by the server from other data on every read, never stored and never sent by a client (absent from WidgetCreate/WidgetUpdate). Forces a read-only badge column, a filter and a sort that the server evaluates, so they hold across pages. */
            readonly checklistState: components["schemas"]["WidgetChecklistState"];
        };
        /** @description Widget without a server-assigned id. tags, extraCategoryIds and checklist default to [], inStock to true. */
        WidgetCreate: {
            name: components["schemas"]["Widget"]["name"];
            categoryId: components["schemas"]["Widget"]["categoryId"];
            status: components["schemas"]["WidgetStatus"];
            availableFrom: components["schemas"]["Widget"]["availableFrom"];
            assigneeEmail?: components["schemas"]["Widget"]["assigneeEmail"];
            price: components["schemas"]["Widget"]["price"];
            description: components["schemas"]["Widget"]["description"];
            tags?: components["schemas"]["Widget"]["tags"];
            inStock?: components["schemas"]["Widget"]["inStock"];
            extraCategoryIds?: components["schemas"]["Widget"]["extraCategoryIds"];
            checklist?: components["schemas"]["Widget"]["checklist"];
        };
        /** @description All fields optional — PATCH semantics. tags, when sent, replaces the whole set (send [] to clear it); so do extraCategoryIds and checklist (which also keeps the order sent). */
        WidgetUpdate: {
            name?: components["schemas"]["Widget"]["name"];
            categoryId?: components["schemas"]["Widget"]["categoryId"];
            status?: components["schemas"]["WidgetStatus"];
            availableFrom?: components["schemas"]["Widget"]["availableFrom"];
            assigneeEmail?: components["schemas"]["Widget"]["assigneeEmail"];
            price?: components["schemas"]["Widget"]["price"];
            description?: components["schemas"]["Widget"]["description"];
            tags?: components["schemas"]["Widget"]["tags"];
            inStock?: components["schemas"]["Widget"]["inStock"];
            extraCategoryIds?: components["schemas"]["Widget"]["extraCategoryIds"];
            checklist?: components["schemas"]["Widget"]["checklist"];
        };
        /**
         * @description none: the checklist is empty. open: at least one item isn't done. complete: every item is done. Sorts in this order.
         * @enum {string}
         */
        WidgetChecklistState: "none" | "open" | "complete";
        /** @description One item of a widget's checklist. No id of its own: the list is read and written whole, in order. */
        ChecklistItem: {
            /** @description What to do. Surrounding spaces are trimmed; blank is a 422. */
            text: string;
            /** @description Ticked off. */
            done: boolean;
        };
        /** @description Wire pagination shape — deliberately not Page<T>. The gateway computes page/pageSize from offset/limit; see src/api/gateway/. */
        WidgetListResponse: {
            items: components["schemas"]["Widget"][];
            total: number;
        };
        /** @description FastAPI's default 422 shape (RequestValidationError). */
        ValidationErrorBody: {
            detail: {
                loc: (string | number)[];
                msg: string;
                type: string;
            }[];
        };
        /** @description FastAPI's default HTTPException shape. */
        HTTPErrorBody: {
            detail: string;
        };
    };
    responses: {
        /** @description Validation failed on one or more fields. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorBody"];
            };
        };
        /** @description Resource not found. */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["HTTPErrorBody"];
            };
        };
        /** @description Missing or invalid credentials. */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["HTTPErrorBody"];
            };
        };
        /** @description Unhandled server error. */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["HTTPErrorBody"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated. Sets the session_id cookie. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["ServerError"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registered and authenticated. Sets the session_id cookie. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            422: components["responses"]["ValidationError"];
            500: components["responses"]["ServerError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out (always, whether or not a session existed). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["ServerError"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["ServerError"];
        };
    };
    getDataEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataEnvironment"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    listWidgetCategories: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring match on name. */
                search?: string;
                /** @description Only these categories, e.g. "ids=1&ids=3" — how a form or table gets the names of references it already holds, whether or not they match the current search. Unknown ids are left out. */
                ids?: number[];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching categories, unpaginated (typeahead result set, not a table). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WidgetCategory"][];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["ServerError"];
        };
    };
    listWidgets: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                /** @description Single sort field and direction, e.g. "name:asc". */
                sort?: string;
                status?: components["schemas"]["WidgetStatus"];
                categoryId?: number;
                /** @description Case-insensitive substring match on name. */
                search?: string;
                /** @description Widgets with any of these tags. Repeat the parameter once per tag, e.g. "tags=fragile&tags=seasonal". */
                tags?: components["schemas"]["WidgetTag"][];
                /** @description Only widgets whose computed checklistState matches. */
                checklistState?: components["schemas"]["WidgetChecklistState"];
                /** @description Only widgets whose inStock matches, sent as "inStock=true" or "inStock=false". Absent means either. */
                inStock?: boolean;
                /** @description Widgets linked to any of these categories through extraCategoryIds. Repeat the parameter once per id, e.g. "extraCategoryIds=1&extraCategoryIds=3". */
                extraCategoryIds?: number[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of widgets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WidgetListResponse"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            500: components["responses"]["ServerError"];
        };
    };
    createWidget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WidgetCreate"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Widget"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["ServerError"];
        };
    };
    getWidget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Widget"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["ServerError"];
        };
    };
    deleteWidget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["ServerError"];
        };
    };
    updateWidget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WidgetUpdate"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Widget"];
                };
            };
            401: components["responses"]["UnauthorizedError"];
            404: components["responses"]["NotFoundError"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["ServerError"];
        };
    };
}
